### ISSUE TITLE
Issue with the Annotation_Tool for MoCap Data

### ISSUE THREAD

**Issue by mayankrichu** [wilfer9008/Annotation_Tool_LARa#10]
Hi, I'm currently working with Annotation Tool LARa to annotate MoCap Data for a project and facing a problem.

The issue is, when I upload the MoCap unlabelled .csv file to the application, it doesn’t show the image of the skeleton.

Could you please help me in solving this issue? Thanks a lot in advance.

Kind regards,
Mayank Singh

**Comment by Halloerik** [comment]
Hi, what is your pyqtgraph version? Sadly in 0.12.3 something has changed which made the widget not work anymore. Please make sure that you have at pyqtgraph 0.12.2 or an earlier version installed.

Best regards,
Erik

**Comment by mayankrichu** [comment]
I changed the pyqtgraph from version 0.12.4 to 0.12.2. Still getting the same empty window. Neverthless, the frame number increases once the file is played.

Below is the error which I'm getting on running main.py

Traceback (most recent call last):
  File "C:\Users\singhm\Anaconda3\lib\site-packages\pyqtgraph\opengl\GLViewWidget.py", line 246, in paintGL
    glViewport(*self.getViewport())
  File "C:\Users\singhm\AppData\Roaming\Python\Python38\site-packages\OpenGL\error.py", line 230, in glCheckError
    raise self._errorClass(
OpenGL.error.GLError: GLError(
	err = 1282,
	description = b'invalid operation',
	baseOperation = glViewport,
	cArguments = (0, 0, 675, 707)
)

**Comment by Halloerik** [comment]
I honestly don't know what to recommend you, since this error is entirely new to me. 

Except for using a new venv and trying to reinstall all the required packages nothing comes to mind. 

Are you using LARa data? If not are you using other data with the same format that LARa data has?
Have you modified the source code? If you did, which parts did you change?

**Comment by mayankrichu** [comment]
Okay. I'll try reinstalling it. 

I'm using the OMoCap data from this link https://zenodo.org/record/3862782#.YqBMWVTP2M9 

The file name ends with norm_data.csv

**Comment by Halloerik** [comment]
yeah that is the right data. It should have worked correctly...

**Comment by mayankrichu** [comment]
Hi, do you think this might be due to the unavailability of the graphics card?

**Comment by mayankrichu** [comment]
Yes! It is working fine now. I just tested on a different system with a graphics card. Thanks for your help. :)
